// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxflcpniB2cGPgHjSAu_-CJylRoj-pqbU',
    appId: '1:6807732779:web:771009ce176a14031ce06e',
    messagingSenderId: '6807732779',
    projectId: 'me-chat-v2',
    authDomain: 'me-chat-v2.firebaseapp.com',
    storageBucket: 'me-chat-v2.appspot.com',
    measurementId: 'G-8SN4MB584D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKofz4kNhofyXvLNlxwUfH5HHXRdUsfmY',
    appId: '1:6807732779:android:e2a52be34109cd571ce06e',
    messagingSenderId: '6807732779',
    projectId: 'me-chat-v2',
    storageBucket: 'me-chat-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2H1pPVaH2eKjHXrsJalc-s3oRs4F9wBo',
    appId: '1:6807732779:ios:2f1eb73829c804a01ce06e',
    messagingSenderId: '6807732779',
    projectId: 'me-chat-v2',
    storageBucket: 'me-chat-v2.appspot.com',
    iosBundleId: 'com.example.meChatUpdate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2H1pPVaH2eKjHXrsJalc-s3oRs4F9wBo',
    appId: '1:6807732779:ios:2f1eb73829c804a01ce06e',
    messagingSenderId: '6807732779',
    projectId: 'me-chat-v2',
    storageBucket: 'me-chat-v2.appspot.com',
    iosBundleId: 'com.example.meChatUpdate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxflcpniB2cGPgHjSAu_-CJylRoj-pqbU',
    appId: '1:6807732779:web:08882379e2de08531ce06e',
    messagingSenderId: '6807732779',
    projectId: 'me-chat-v2',
    authDomain: 'me-chat-v2.firebaseapp.com',
    storageBucket: 'me-chat-v2.appspot.com',
    measurementId: 'G-4BH5WG3ZG0',
  );
}
